### ISSUE TITLE
Write basic README

### ISSUE THREAD

**Issue by machow** [datacamp/antlr-ast#8]
- [x] building a grammar
- [ ] overview of ASTNode, Speaker
- [x] reference to part of test that writes a parse function
- [x] running tests
- [x] only python3 compatible

**Comment by hermansje** [comment]
[See also this issue](https://github.com/datacamp/ast-viewer/issues/12)

**Comment by machow** [comment]
whoops, also need 

- [ ] explain `_rules` class attribute

**Comment by hermansje** [comment]
I added some notes in the code that can be used for the `_rules` explanation: #10
